### ISSUE TITLE
Provide an interface similar to fsatrace

### ISSUE THREAD

**Issue by ndmitchell** [droundy/bigbro#6]
At the moment it appears `bigbro` writes things to stdout, which means that telling what is legitimate  program output and what is tracing is hard. Would it be possible to have it take the location to write to as an argument? Supporting the same command line as fsatrace would be ideal, as then I could let users pick as they chose (e.g. if they are using `go`).

**Comment by droundy** [comment]
That would be fine. The executable is not really designed to be used, as
bigbro is designed as a library. The executable was just created to enable
integration testing.

David Roundy

**Comment by droundy** [comment]
Actually, can you be a bit more explicit? I'm realizing I don't know the interface of fsatrace, and having it laid out here would be helpful.

**Comment by droundy** [comment]
I presume from your request that using bigbro as a library is not an option for you? I feel like a library interface is far preferable to an executable that you must locate and execute, which writes to a pipe you must read from and then parse, but I suppose if you're already doing all that work, maybe it is the easiest way?

**Comment by ndmitchell** [comment]
The interface to fsatrace is described at https://github.com/jacereda/fsatrace#usage, but to give the summary, you run:

```
fsatrace rwm traceoutput.txt -- command line
```

And it runs `command line`, watching for `rwm` (read, write, move in this case - you can also do `t` for touch and a few others), then it writes to `traceoutput.txt` a list of lines `r|/file/that/was/read`, `w|/file/written`, `m|/move/from|move/to`. The `traceoutput.txt` can be `-` in which case info goes on stdout.

Shake already uses `fsatrace` as a command line, so a compatible `bigbro` command line would let people switch them freely. For Shake, I deliberately have very few dependencies, so an executable lets it become an optional dependency. People may not have `fsatrace` or `bigbro` installed to start with, especially when bootstrapping, but may turn it on only on CI - it provides a linting feature, so its useful, but optional. As a result, a loose coupling works quite nicely.

**Comment by droundy** [comment]
I'm finally getting around to this (it's summer!) and wanted to check on your needs.  bigbro doesn't treat moves specially (or does?) and has a lot fewer outputs.

A move of a file deletes the old file and writes to the new file.  If the old file was created then there is no mention of the old file, so you don't need to track that as a user.

A stat operation is treated as a read, if it is operating on a file.

A readdir is treated differently from a read.  This is easy to unify with "reads" in the fsatrace output if that is desired.  Or does fsatrace simply ignore readdirs?

Touch is treated like a write.

Can you let me know what combination you use, and what would be useful in the output?

**Comment by ndmitchell** [comment]
Great news!

For moves, I always decompose them afterwards into a read/write pair anyway, so feel free to output moves or the constituent pieces, whichever is easiest.

I think fsatrace ignores readdir. I'd be tempted to say invent a code for that (e.g. `l` for "list") and output it as a brand new code. I can have Shake etc. parse the superset of both and deal with both fsatrace and bigbro in one.

Touch as write is fine, I treat that as equivalent anyway.

In general, if you just spit out whatever you have in the most direct form you have, but following the same spirit of interface, then unifying them should be pretty easy.

**Comment by droundy** [comment]
You should be able to just run `cargo install bigbro` and get the executable bigbro-fsatrace somewhere in your path I think.  But this is actually not something I've tested.

**Comment by ndmitchell** [comment]
Thanks! I'm away from my Shake machine for a few weeks but will give it a go when I get back.

**Comment by ndmitchell** [comment]
Doing `cargo install bigbro` gave me:

```
   Installed package `bigbro v0.5.1` (executables `bigbro-fsatrace.exe`, `echo.exe`, `false.exe`, `ls.exe`, `test-bigbro-chan.exe`, `test-bigbro-scaling.exe`, `test-bigbro-twostep.exe`, `test-bigbro.exe`, `touch.exe`)
```

Having echo, false, ls etc hijacked by bigbro is not particularly welcome - I imagine that's going to confuse my machine horribly at some future date...

**Comment by droundy** [comment]
I've just pushed a change removing these, which were intended for test suites on windows that never got used.

**Comment by ndmitchell** [comment]
Thanks! Much appreciated. I've got it installed, just need half an hour to actually try and use it.
